config/routes.rb
Rails.application.routes.draw do
  get 'game', to: 'longestword#game'

  get 'score', to: 'longestword#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/longestword_controller.rb
class LongestwordController < ApplicationController
 require 'open-uri'
 require 'json'
 require 'time'

 KEY = 'fb27f491-aea6-49b7-8508-025e689c3978'
 URL = 'https://api-platform.systran.net/translation/text/translate?source=en&target=fr&key='

  def game
    # Build the grid
    @grid = generate_grid(13).join(' ')
    @start_time = Time.now
  end

  def score
    # Retrieve all game data from form
    grid = params[:grid].split("")
    @attempt = params[:attempt]
    start_time = Time.parse(params[:start_time])
    end_time = Time.now
    # Compute score
    @result = run_game(@attempt, grid, start_time, end_time)
  end

  private

  def run_game(attempt, grid, start_time, end_time)
    result = {}
    result[:time] = (end_time - start_time).to_i
    case_analyze(attempt, result, grid)
    result
  end

  def case_analyze(attempt, result, grid)
    if !check_grid(attempt, grid)
      result[:score] = 0
      result[:message] = 'Not in the grid !'
    elsif check_word(attempt) == attempt
      result[:score] = 0
      result[:message] = 'Not an english word !'
    else
      result[:translation] = check_word(attempt)
      result[:score] = (attempt.length * 100 / result[:time].to_f).round(2)
      p result[:score] #/
      result[:message] = 'Well done !'
    end
    result
  end

  def generate_grid(grid_size)
    grid = []
    grid_size.times { grid << ('A'..'Z').to_a.sample }
    grid
  end

  def check_grid(attempt, grid)
    attempt_h = check_occurence(attempt.upcase.chars)
    grid_h = check_occurence(grid)
    attempt_h.each do |key, value|
      return false unless grid_h.key?(key)
      return false if value > grid_h[key]
    end
    true
  end

  def check_occurence(chars)
    hash = {}
    chars.each do |char|
      hash.key?(char) ? hash[char] += 1 : hash[char] = 1
    end
    hash
  end

  def check_word(attempt)
    JSON.parse(open(URL + KEY + '&input=' + attempt).read)["outputs"][0]["output"]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/longestword_helper.rb
module LongestwordHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Des chiffres et des lettres</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/longestword/game.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 text-center myword">
      <h1>Des chiffres & des lettres</h1>
      <h2>Votre Grille</h2>
      <h3><%= @grid %></h3>
      <h2>Que proposer vous ?</h2>
      <form action="<%= score_path %>" classs= "form-group" method="get">
        <input type="text" name="attempt">
        <input type="hidden" name="grid" value="<%= @grid %>">
        <input type="hidden" name="start_time" value="<%= @start_time %>">
        <input type="submit" value="GO" class = "btn btn-primary">
      </form>
    </div>
  </div>
</div>

app/views/longestword/score.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 text-center myword">
      <h1>Votre Score !</h1>
      <h2>Resultat</h2>
      <h3>Votre mot: <%= @attempt %></h3>
      <h3>Temps de reponse: <%= @result[:time] %> secondes</h3>
      <h3>Traduction: <%= @result[:translation] %></h3>
      <h3>Votre Score: <%= @result[:score]%></h3>
      <h3><%= @result[:message]%> </h3>
      <h4><%= link_to "Rejouer", game_path, class: "btn btn-primary" %></h4>
    </div>
  </div>
</div>